conda/linux_dev/AppDir/AppRun, conda/linux_stable/AppDir/AppRun
The issue of git using the wrong certificate verify location (/home/travis/build/FreeCAD/FreeCAD-AppImage/conda/linux_stable/AppDir/usr/ssl/cacert.pem) has been reported here:
https://forum.freecadweb.org/viewtopic.php?t=36255
https://forum.freecadweb.org/viewtopic.php?f=12&t=36210
https://forum.freecadweb.org/viewtopic.php?f=10&t=34981&start=20#p300154
https://forum.freecadweb.org/viewtopic.php?t=35477
As far as I can tell, this absolute path from the travis build is baked into the curl library. However it seems git can be told to pass an alternative location to curl using the GIT_SSL_CAINFO environment variable, so this is the solution proposed here. This change to the AppRun script fixed the problem on for me.
=> Tell git to use the correct path for CA certificate

conda/linux_dev/AppDir/AppRun, conda/linux_dev/linux_dev.sh, conda/osx_dev/APP/FreeCAD.app/Contents/MacOS/FreeCAD, conda/osx_dev/osx_dev.sh
This will help to debug issues with dependencies. It simple writes all dependencies installed in the environment created on travis into a file and prints this file when the user starts the application.
It's also possible to print this information only if the user adds an option like (--deps). But I am not sure how we can distinguish between options passed to freecad and options which should be handled by the appimage/dmg.
@triplus
=> print installed dependencies during startup

conda/osx_dev/APP/FreeCAD.app/Contents/MacOS/FreeCAD, conda/osx_dev/osx_dev.sh
@triplus I didn't push directly as I saw you are working on the appimage. Maybe you have some time to merge this one. I have tested it localy and it should fix the addon-manager problem on osx:
https://forum.freecadweb.org/viewtopic.php?f=3&t=42825
=> osx: add ssl_cert_file variable

conda/osx/create_bundle.sh
all macOS apps are supposed to have a CFBundleIdentifier. native preferences and caching will be broken without it.
=> fix bug that FreeCAD does not have a bundle identifier

make_version_file.py
based on https://github.com/FreeCAD/FreeCAD/blob/10888e7aad50d9a8162f8f3df8dedbd83dca1db1/src/Tools/SubWCRev.py#L205
I have not tested this but it should give more complete version info
FYI here's the automatic Version.h when building freecad from a git repository:
```
// Version Number
#define FCVersionMajor "0"
#define FCVersionMinor "20"
#define FCVersionName  "Vulcan"
// test: $Format:Hash (%H), Date: %ci$
#define FCRevision      "28901 (Git)"      //Highest committed revision number
#define FCRevisionDate  "2022/05/17 14:43:53"     //Date of highest committed revision
#define FCRepositoryURL "/I/censored/the/path/FreeCAD master"      //Repository URL of the working copy
// Git relevant stuff
#define FCRepositoryHash   "a5ff51580400894977021fbdac674b771984c243"
#define …
```
=> Also save commit hash and branch info to Version.h

make_version_file.py
Reusing existing functionality from the FreeCAD source, this has the added benefit of including the repo url that enables the functionality of having a link to the commit in the about dialog. To take advantage of this in the conda builds #117 should be solved.
=> Rewrite make_version_file.py

conda/linux/AppDir/AppRun
Allows to import freecad when running python console from appimage
=> [fixes #103] set PATH_TO_FREECAD_LIBDIR env var

.github/workflows/freecad_bundle.yml
https://github.com/isaacs/node-glob/issues/480
according to this we should also use forward slashes for the glob pattern even on windows
=> fix windows assets upload

conda/win_py310/create_bundle.bat, conda/win_py38/create_bundle.bat
See https://forum.freecad.org/viewtopic.php?t=77052
```
OS: Windows 7 Version 6.1 (Build 7601: SP 1)
Word size of FreeCAD: 64-bit
Version: 0.21.0.32532 (Git)
Build type: Release
Branch: master
Hash: 20e44eba50e1365b9e7bb9c5c244afe96a627a28
Python 3.8.16, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
Installed mods: 
```
=> Fix Qtwebengine translation warnings

conda/linux/create_bundle.sh, conda/osx/create_bundle.sh
Now that a 10.0 package is available it's picking that but freecad was built against 9.1.0, this is a workaround while https://github.com/conda-forge/freecad-feedstock/pull/91 is not merged yet
=> Specify fmt version for linux and macOS bundles

conda/osx/create_bundle.sh, conda/scripts/fix_rpaths.py
Changes on top of ccef8eb4083ae038aa86ea1001de7ee136da1350 fixes signatures for libraries modified by `install_name_tool`
Additional changes according to findings in https://github.com/FreeCAD/FreeCAD/issues/10144#issuecomment-1847657394
I ran the `create_bundle.sh` to build new FreeCAD.app bundle. The bundle does not contain rpaths with absolute paths and the app does not crash when launched.
cc: @adrianinsaval
=> macOS: fix rpaths in macOS CI builds

conda/linux/create_bundle.sh, conda/osx/create_bundle.sh, conda/win/create_bundle.bat
See forum discussion https://forum.freecad.org/viewtopic.php?t=84536 it appears that `ifcopenshell` doesn't bring in the lark dependency, therefore adding to the bundles.
=> [Conda] Add Python-lark to all three platforms

conda/osx/create_bundle.sh, conda/osx/dmg_settings.py
This uses `dmgbuild` to create a DMG with bigger icons and a symlink to `/Applications`. As it does not yet contain a background image or color, it adapts to dark and light mode settings:
Partially addresses #242.
=> macOS: Add symlink to /Applications and use bigger icons

conda/osx/create_bundle.sh
This should fix the build on the arm machine. Using `--break-system-packages` should be safe as we don't use system python for anything else.
Other options would be to use `pipx` or a install it in a virtual environment. Both seem overcomplicated for an automated build.
/cc @adrianinsaval
=> Add --break-system-packages pip install dmgbuild

conda/osx/launcher/FreeCAD.cpp
FreeCAD uses argv[0] to determine PREFIX information, not the environment variables. This commit corrects argv[0] to match the FreeCAD binary.
=> Fix macOS launcher app.

README.md
Part of campaign (#299) to stop errant bug reports in the wrong repo.
Preview: https://github.com/FreeCAD/FreeCAD-Bundle/blob/README/README.md
=> README: Reorientation toward curbing incorrect FreeCAD main bugreports

.github/ISSUE_TEMPLATE/bug-report.md
Added another level of abstraction against incorrect filing of bugs.  
Closes #299
Preview: https://github.com/FreeCAD/FreeCAD-Bundle/blob/issue-template/.github/ISSUE_TEMPLATE/bug-report.md
=> Add bug report issue template (#299)

conda/osx/Info.plist.template
Some users have been experiencing FreeCAD's title bar being in the light theme instead of adopting system theme conventions.  This change the `Info.plist` is intended to force using system theme by default.
https://forum.freecad.org/viewtopic.php?t=56992
=> macOS: Use system theme for title bar.

conda/linux/create_bundle.sh, conda/osx/create_bundle.sh, conda/win/create_bundle.bat
Currently `numpy>=2` have issues when installed from conda-forge.  Furthermore, VFX Platform currently standardizes on `numpy==1.26`.
This PR pins numpy to 1.26 which should resolve the current issues plaguing recent releases and ensuring compatibility with other VFX Platform compliant systems.
=> Pin numpy to 1.26.x

README.md
Part of https://github.com/FreeCAD/FreeCAD/issues/22803
Fixes https://github.com/FreeCAD/FreeCAD-Bundle/issues/425
Clarifies where archived weekly builds can be downloaded.
Also little re-structuring of the text.
=> Update README with link to archived builds on main repo
